function [trans_prob,...
          sigma,...
          B_matrix,...
          lamdas,... 
          residuals, params, x0] = m_step(smth_prob,...
                                      smth_joint_prob,...
                                      residuals_old,...
                                      delta_yt,zt,x0)
%M_STEP Summary of this function goes here
%   Detailed explanation goes here
trans_prob = tans_prob_estimate(smth_prob,smth_joint_prob); % done 
[sigma,...
 B_matrix,...
 lamdas,x0] =  sigma_estimate(residuals_old,smth_prob,x0);% done
params = wls_estimate(sigma, smth_prob,delta_yt,zt);
residuals = res_estimate(params,delta_yt,zt);
%print not completed
end

